### ISSUE TITLE
AssertionError: Unexpected shape of `moments`.

### ISSUE THREAD

**Issue by bjnorfolk** [richteague/bettermoments#19]
Hi, 
I'm attempting to make a moment 9 cube fits but I get the error above. Here's my current usage of bettermoments:
```python 
bettermoments cube.fits -method ninth -clip 4 -firstchannel 5 -lastchannel 64
```
Out:
``` python
Loading up data...
Loading up user-defined mask...
Defining channel-based mask...
Smoothing the data...
Estimating noise in the data...
Estimated RMS: 9.82e-04.
Calculating threshold-based mask...
Masking the data...
Calculating maps...
Saving maps...
Traceback (most recent call last):
  File "/home/bnorfolk/anaconda3/envs/py38/bin/bettermoments", line 8, in <module>
    sys.exit(main())
  File "/home/bnorfolk/anaconda3/envs/py38/lib/python3.8/site-packages/bettermoments/collapse_cube.py", line 439, in main
    save_to_FITS(moments=moments,
  File "/home/bnorfolk/anaconda3/envs/py38/lib/python3.8/site-packages/bettermoments/io.py", line 258, in save_to_FITS
    assert moments.ndim == 3, "Unexpected shape of `moments`."
AssertionError: Unexpected shape of `moments`.
```

**Comment by richteague** [comment]
Hi Brodie! Can you try updating `bettermoments` (v1.6.5) to the latest version and see if that fixes it? I think I fixed error recently.

**Comment by bjnorfolk** [comment]
Hi Richard,

The update has fixed the error. Thanks!

**Comment by richteague** [comment]
Great, glad to hear it!
